#!/bin/bash
#set -e
set -x
# artifacts="jar war ear"
# moved="false"
target="${ODO_S2I_SRC_BIN_PATH}/src/target"

ls -lR ${ODO_S2I_SRC_BIN_PATH}/src

if [[ -d $target ]]; then
    echo "Found old artifacts, backing it up"
    mv $target $target.bak
fi

# run normal assemble script
if ${ODO_S2I_SCRIPTS_URL}/assemble; then
    exit 0
else
    # If it failed, restore any previous artifacts and rebuild
    if [[ ! -d $target.bak ]]; then
        exit 1
    fi
    echo "Restoring previous build"
    mv $target.bak $target
    ${ODO_S2I_SCRIPTS_URL}/assemble
    exit 1
fi
